version: '3.8'

services:
  app:
    image: sonuafriza/rekos-laravel:latest 
    ports:
      - "8000:80" 
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=rekos_db
      - DB_USERNAME=root
      - DB_PASSWORD=123qweasd
    volumes:
      - rekos_storage:/var/www/html/storage/app/public
      - ./.env:/var/www/html/.env
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123qweasd
      - MYSQL_DATABASE=rekos_db
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  - /var/www/html/rekos-laravel/.env:/var/www/html/.env
  - /var/www/html/rekos-laravel/storage/app/public:/var/www/html/storage/app/public

networks:
  default:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: "1400"